### ISSUE TITLE
Whole genome SNP association

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2scan#105]
Add ability to do SNP associations scan across the whole genome.

**Comment by dmgatti** [comment]
I would also include a way to easily subset the SNPs that are returned by this method. Currently, I get back scan1 and snpinfo objects and try to subset them myself.  It's a lot of work to get the mapping from scan1 to the snpinfo to work out correctly (or perhaps I'm missing the simple function that does it...).
I could see three types of subsetting operations:
1. Filter by physical location. (e.g. I scanned over a 10 Mb region, but I only want to plot a 2 Mb region.
2. Filter by LOD. (e.g. I only want to keep SNPs with LOD > 3)
3. Filter by consequene. (e.g. I only want splice/stop and missense SNPs)

**Comment by kbroman** [comment]
Sounds great! Currently working on formalizing the treatment of SNPs (and genes), in [qtl2db](https://github.com/rqtl/qtl2db). Will work on this next.

**Comment by kbroman** [comment]
@dmgatti: I've also been thinking about doing GWAS with the raw SNP data. Do you think that's something folks would want? One issue is that the nature of the "raw" genotypes is different by cross type.

**Comment by kbroman** [comment]
I'd added `scan1snps()` which can do a genome scan at SNPs. Still need to implement the filtering ideas. I think combine LOD scores and snp info into a single data frame (e.g. via `top_snps()`) and then leave filtering to the user.
