### ISSUE TITLE
Drop dependent covariate columns after dropping individuals

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2scan#76]
In `scan1()` and related functions, detect and drop linearly dependent covariate columns **after** dropping individuals that don't appear in all data objects.

For example, if you have batch 2,3,4 indicators as covariates and a phenotype is measured only in batches 1 and 2, you need to drop the indicators for batches 3 and 4, but that's not obvious until you've reduced the individuals.

**Comment by simecek** [comment]
Sometimes, not dropping the column makes `scan1()` output `NaN` (all LODs are `NaN`).

I am using the following solution to generate covars on a fly. 

``` 
# check present/missing values for i-th phenotype
present <- !is.na(pheno[,i])

# subset LOCO kinship matrices
for (j in 1:20)
    Glist2 <- Glist[[j]][present,present]

# generating covars on a fly
if (length(unique(annot.samples$GenerationLitter[present]))>1){
    addcovar <- model.matrix(~ Sex + Diet + GenerationLitter, data=annot.samples[present, ])
  } else {
    addcovar <- model.matrix(~ Sex + Diet, data=annot.samples[present, ])
  }  
 
# scan function itself 
tmp <- scan1(genoprobs=probs[present,], 
               kinship=Glist2, 
               pheno=pheno[present,i], 
               addcovar=addcovar, 
               cores=ncores, 
               reml=TRUE)
```

But less experienced users in our lab run into this issue previously and did not know what to do. It would be nice if `qtl2` somehow tests for that or (at least) throws a warning.

**Comment by kbroman** [comment]
In your last sentence, by "test for that" do you mean testing for linearly dependent columns?

**Comment by simecek** [comment]
In my example, it would be sufficient to test there are at least two different values in each column and drop the column otherwise.
