### ISSUE TITLE
transform vcf file for rqtl

### ISSUE THREAD

**Issue by rajanikanthnmsu** [rqtl/qtl2scan#9]
Dear Dr. Broman,

I have a vcf file from variant calling of whole genome sequences from 120 RILs and have about 5 million variants that i want to use in Rqtl for QTL mapping.Please suggest me if there is any tool that can parse the vcf to create an input file for Rqtl.

Thank you very much.

Rajanikanth

**Comment by kbroman** [comment]
I'm not aware of any.

**Comment by kbroman** [comment]
(Closed because this would fit better as an issue for [R/qtl](https://github.com/kbroman/qtl), or perhaps for [qtl2geno](https://github.com/rqtl/qtl2geno).)
